- .goreleaser.yml
- CHANGELOG.md
- README.md
- fastcopy.tmux
- install.sh
If a Go compiler is not available, or we fail to build from source for
any reason, attempt to download pre-built binaries from GitHub--if
available.
Add a release check to verify that the version in the install.sh matches
the version being released.
> Download binary from Github if Go is unavailable

- README.md
- app.go
- config.go
- config_test.go
- internal/iotest/writer.go
- internal/iotest/writer_test.go
- internal/log/logtest/logger.go
- internal/paniclog/handle.go
- internal/paniclog/handle_test.go
- internal/tmux/tmuxopt/tmuxopt.go
- internal/tmux/tmuxopt/tmuxopt_test.go
- internal/ui/annotated_text.go
- main.go
- main_test.go
- matcher.go
- matcher_test.go
- widget.go
- wrap_test.go
Adds support for custom regular expressions. At its core, this
functionality is supported by the CLI flag:
--regex NAME:REGEX
Where `NAME` uniquely identifies this pattern and will overwrite prior
instances of this name (making it possible to override default regular
expressions).
However, most users will probably use the tmux.conf:
set -g @fastcopy-regex-NAME REGEX
Where `NAME` and `REGEX` are specified by the user.
In implementing this, I ran into some issues with overlapping matches
from regular expressions, so this addresses that too. Overlapping
regular expressions are cleaned up in favor of the longest matches.
Finally, if a regular expression has a capture group `(...)`, then the
first capture group will be the captured text rather than the whole
match. This makes it easier to …
> Support custom regular expressions

- CHANGELOG.md
- README.md
- action.go
- main.go
`tmux set-buffer` needs the `-w` flag to write to the client's clipboard.
> Default action should write to clipboard

- Makefile
The `pwd` approach doesn't work in a multi-makefile situation.
MAKEFILE_LIST will always give a path relative to the current Makefile.
> make: Use MAKEFILE_LIST to determine path

- CHANGELOG.md
- action.go
- app.go
- config.go
- config_test.go
- main.go
- main_test.go
- wrap.go
- wrap_test.go
Add `-log` and `-tmux` flags to specify the location of the log file and the
tmux executable. `-log` deprecates the `TMUX_FASTCOPY_LOG` environment
variable.
> Add -log and -tmux flags

- .github/workflows/integration.yml
- CHANGELOG.md
- README.md
- config.go
- integration/integration_test.go
- internal/tmux/shell.go
- internal/tmux/shell_test.go
- main.go
The `-e` flag of `new-session` was added in Tmux 3.2. We can support
tmux 3.1 by instead shelling out to `/usr/bin/env` and using that to set
the environment variables.
> Support Tmux 3.1c

- .github/workflows/integration.yml
- CHANGELOG.md
- README.md
- app.go
- integration/Makefile
- internal/tmux/driver.go
- internal/tmux/inspect.go
- internal/tmux/shell.go
- internal/tmux/shell_test.go
- internal/tmux/tmuxtest/mocks.go
The `-Z` flag for `swap-pane` was added in Tmux 3.1. We can do without
it by explicitly resizing the window if it's zoomed. This will cause
a slight flicker for zoomed windows, but it might be an acceptable
tradeoff.
> Support Tmux 3.0

- CHANGELOG.md
- install.sh
Release v0.4.0 of tmux-fastcopy with support for tmux 3.0.
> Prepare release v0.4.0

- CHANGELOG.md
- internal/huffman/huffman.go
- internal/huffman/huffman_test.go
If there's a single entry in the collection of matches, our huffman
implementation will return an empty label. That results in an infinite
loop when rendering because we attempt to match empy input to an empty
label.
Resolve this by handling the single match case separately.
Fixes #38
> Fix infinite loop on single match

- CHANGELOG.md
- internal/tail/tail.go
The way log tailing was implemented, we were effectively spin looping
when the source had no bytes to produce but also had not yet hit EOF.
while !eof {
read(f)
}
Fix this by spinning only if it had bytes to produce (indicating that
there may be more), and once it begins producing zero bytes, use the
same delay we would use for EOF.
do {
n = read(f)
} while (n > 0 && !eof)
if eof || n == 0 { sleep; retry }
This resolves 100% CPU usage when idling.
Fixes #38
> log/tail: Don't consume 100% CPU when idle

- app.go
- internal/envtest/env_test.go
- internal/fastcopy/hint.go
- internal/fastcopy/hint_test.go
- internal/fastcopy/widget.go
- internal/huffman/huffman_test.go
- internal/log/log_test.go
- matcher.go
Move main.Widget and friends to an internal package and
test the hint/annotation generation logic separately.
Remove redundant empty annotations generated for hints.
Fill in minor pieces of missing coverage in
envtest, huffman, and log.
> Test hint and annotation generation

- CHANGELOG.md
- internal/tmux/tmuxopt/tmuxopt.go
- internal/tmux/tmuxopt/tmuxopt_test.go
We use `strconv.Unquote` to unquote quoted strings from the Tmux
configuration.
However, this function only unquotes Go string literals.
Single-quoted strings are not valid string literals.
strconv.Unquote(`'foo'`)
// error: invalid syntax
Fix this by inverting the quotes on single-quoted strings, handing off
to strconv.Unquote, and inverting the result back.
Resolves #48
> tmux options: Handle single-quoted strings

- CHANGELOG.md
- integration/integration_test.go
- internal/tmux/shell.go
- internal/tmux/shell_test.go
- internal/ui/text.go
- internal/ui/text_test.go
When a line is longer than the width of the pane,
tmux wraps it like so:
|foob|
|ar  |
`tmux capture-pane` reports these as two separate lines by default.
$ tmux capture-pane
foob
ar
This means that really long strings that would otherwise be matched by
tmux-fastcopy get split and possibly ignored.
We can address this by using the `-J` flag of `tmux capture-pane`,
which provides a more accurate representation of the actual text
on-screen.
$ tmux capture-pane -J
foobar
Combining that with some basic record-keeping of the screen width, we
can show the user the wrapped text, and still copy the actual unwrapped
text.
Testing this required making the integration test slightly more robust.
---
Before:
After:
> Handle line wrapping

- internal/huffman/huffman_test.go
The alphabet type wasn't using this at all.
> huffman/test: Delete unused field "reverse"

- CHANGELOG.md
- README.md
- action.go
- action_test.go
- app.go
- config_test.go
- internal/fastcopy/hint.go
- internal/fastcopy/hint_test.go
- internal/fastcopy/mock_handler_test.go
- internal/fastcopy/widget.go
- internal/fastcopy/widget_test.go
- main.go
- matcher.go
Pass the name of the matched regular expression to the action via the `FASTCOPY_REGEX_NAME` environment variable.
If multiple regular expressions matched the text, the environment variable holds a space-separated list rather than a singular value.
Refs #56
> Pass regex names to action

- integration_test.go
In the fake tmux, ignore generic IO errors in addition to EOF and closed
errors.
> integration test: Ignore I/O errors

- README.md
What's the point of putting in all that effort to incorporate
integration test coverage data if we're not getting a badge for it?
> README: Add codecov badge

- CHANGELOG.md
- README.md
- app.go
- app_test.go
- config.go
- config_test.go
- integration_test.go
- internal/fastcopy/widget.go
- internal/fastcopy/widget_test.go
- internal/tmux/tmuxtest/matchers.go
- main.go
Add support for specifying an alternative action if the Shift key is
pressed at the time the label is selected.
By default, this new option is a no-op.
Resolves #56
> Support fastcopy-shift-action

- .github/workflows/release.yml
- .goreleaser.yml
goreleaser does not update release notes
if changelog.skip is true
even if --release-notes is passed.
Drop it to resolve the issue.
Related: abhinav/stitchmd#54
Related: abhinav/stitchmd#53
Related: abhinav/doc2go#87
> ci/release: Fix release notes

- CHANGELOG.md
- internal/ui/app.go
- internal/ui/app_test.go
Rendering at 25 FPS causes occasional flickering
on some of the lower end machines.
This fixed rate of rendering isn't necessary
since tmux-fastcopy's UI widget is quite simple.
Switch to event-based rendering:
render after processing each event.
The rate at which we receive events is quite low,
so this shouldn't be an issue.
> ui: Don't use a render loop

- .goreleaser.yml
(Ab)use name_template to achieve the same pattern
to avoid breaking existing users and scripts.
> goreleaser: archive.replacements is deprecated

- .github/workflows/go.yml
Run lint in a separate concurrent job
instead of running it repeatedly in all N test jobs.
> ci/lint: Run in a separate job

- .golangci.yml
- integration/integration_test.go
- internal/fastcopy/widget_test.go
- internal/tail/tail_test.go
- internal/ui/annotated_text_test.go
- internal/ui/app_test.go
This verifies that all tests use t.Parallel,
versus just verifying correct usage of t.Parallel.
> ci(lint): tparallel => paralleltest

- .changes/unreleased/Changed-20230611-122531.yaml
- README.md
- action.go
- action_test.go
- app.go
- doc/opt-action.md
- integration/integration_test.go
- internal/tmux/inspect.go
- internal/tmux/inspect_test.go
- main.go
If the pane inside which tmux-fastcopy is invoked
makes the pane directory available via `pane_path`,
run the action inside that directory
instead of the process' current directory.
Includes a failing test case,
verifying that the directory that we run the fastcopy-action in
matches the directory of the pane when the action is invoked.
Resolves #148
> action: Run inside pane directory

- .changes/unreleased/Added-20230618-145035.yaml
- README.md
- action.go
- action_test.go
- app.go
- doc/README.md
- doc/howto-regex-name.md
- doc/howto-select.md
- doc/opt-action.md
- doc/opt-shift-action.md
- integration/integration_test.go
Sets FASTCOPY_TARGET_PANE_ID when running actions
to the ID of the pane where tmux-fastcopy was invoked.
This may be used with `tmux` operations (usually with the `-t` flag)
to run operations against that pane from within the action.
Resolves #155
> Run actions with FASTCOPY_TARGET_PANE_ID set

- README.md
- doc/howto-select.md
The action should be single quoted for tmux to expand `~` to home.
> doc(howto-select): Action should be single quoted

- .changes/unreleased/Fixed-20231015-123720.yaml
- integration/integration_test.go
- internal/tmux/driver.go
- internal/tmux/shell.go
- internal/tmux/shell_test.go
- internal/tmux/tmuxopt/tmuxopt.go
- internal/tmux/tmuxopt/tmuxopt_test.go
- internal/tmux/tmuxtest/mock_driver.go
- wrap.go
- wrap_test.go
tmux supports a session option 'destroy-unattached' which, when set,
terminates unattached sessions very quickly.
This is a problem for tmux-fastcopy
because it places its temporary window in an unattached session
so as not to have a flicker at the bottom of the user's current session.
Unfortunately, there doesn't appear to be an obvious/easy way
to spawn a session with the option unset *just for it*.
As a workaround, if the user has destroy-unattached set,
the wrapper program will temporarily disable it,
and re-enable it after tmux-fastcopy exits.
Resolves #160
> fix: Don't hang when destroy-unattached is set

- .goreleaser.yml
Per https://goreleaser.com/deprecations/#brewstap,
the brews.tap option has been replaced with brews.repository.
> goreleaser: brews.tap => brews.repository

- .changes/unreleased/Fixed-20241127-171732.yaml
- internal/huffman/huffman.go
- internal/huffman/huffman_test.go
The huffman algorithm works by building a tree
where each node has up to $base children (for a $base alphabet).
High frequency nodes are near the root of the tree,
and low frequency nodes are near the bottom.
Path from root to leaf nodes is the label for that item.
Previously, when building the tree,
we would cluster the items with the lowest frequency
into a node of size $base.
This would result in cases where the topmost nodes (highest frequency)
have fewer than $base children.
So when we assign labels, a few items end up in a lower level
than they could given their frequency and room in the topmost nodes.
So e.g. if there are 4 nodes (A-D), and base is 3. we create the tree:
*
/|
0/ |1
D  *
/|\
0/ |1\2
A  B  C
This results in the labels:
D: 0
A: 10
B: 11
C: 12
This PR changes the …
> huffman: optimize label assignment slightly
